### ISSUE TITLE
[Feature request] Redirect to alternatives (ex. Invidious instead of YouTube)

### ISSUE THREAD

**Issue by dieser-niko** [TEMtheLEM/araa-search#4]
Hi there,

I host a few other search instances like [LibreY](https://github.com/Ahwxorg/librey/), [Whoogle](https://github.com/benbusby/whoogle-search), [4get](https://git.lolcat.ca/lolcat/4get) and of course yours.

One feature in Whoogle that I really like is replacing links to YouTube, Reddit, etc. with some other sites like [Invidious](https://github.com/iv-org/invidious), [RedLib](https://github.com/redlib-org/redlib) (a fork of Libreddit), etc.
Whoogle does this with a set of predefined [Environment Variables](https://github.com/benbusby/whoogle-search?tab=readme-ov-file#environment-variables)

I've tested all these search front ends and have to say that yours looks and feels the best, but the redirection to Invidious and RedLib is something I really miss.

**Comment by Extravi** [comment]
hey this isn't the main repository Extravi/araa-search is

**Comment by dieser-niko** [comment]
Just realized it as well, I'll replicate the issue there.
