### ISSUE TITLE
Publish arm64 images

### ISSUE THREAD

**Issue by laurentlbm** [TEMtheLEM/araa-search#5]
Can you publish `linux/arm64` images so that it can easily be run on a Raspberry Pi or ARM cloud instance?

**Comment by TEMtheLEM** [comment]
I can look into doing this

**Comment by TEMtheLEM** [comment]
Try `docker.io/temthelem/araa-search:beta`. I don't have a native arm device so I can't really do much for testing there.

Images are a little big because 32 bit platforms seem to need to build lxml. I'll see what I can do to maybe shrink their sizes a bit.

**Comment by laurentlbm** [comment]
Thank you, it works! I'm not sure 32-bit support is necessary, maybe you could limit yourself to amd64 and arm64 images for now.
