### ISSUE TITLE
Main url has a 504 time-out error.

### ISSUE THREAD

**Issue by patyarishimai** [TEMtheLEM/araa-search#7]
The main instance, which url is https://search.ttj.dev/, has a 504 gateway time-out error. The same goes for tailsx.com as both of them are maintained, to my knowledge, by @TEMtheLEM.
Hopefully both instances solve the problem as both of them are pretty useful for google-based anonymous results.

I'm adding a screenshot of the pretty-well-known error.

![Screenshot_2024-09-01-23-16-16-297_org mozilla firefox](https://github.com/user-attachments/assets/19c16bef-7c61-462a-95a6-fe4e09824751)

**Comment by Extravi** [comment]
https://araa.extravi.dev/ is up and running
